apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: torrent
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: torrent
    repoURL: https://github.com/code-by-tomislav/manifests.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true